### ISSUE TITLE
Fax.File.Pdf.Bytes returns JSON if API returns error 

### ISSUE THREAD

**Issue by jnankin** [phaxio/phaxio-dotnet#11] opened 2017-10-15 22:14 UTC
If the API returns an error when an attempting to access the fax file (say, 429 rate limit exceeed), fax.File.Pdf.Bytes apparently returns the JSON.  It should raise an exception instead

**Comment by noelherrick** [comment] 2017-10-19 02:19
ETA on this is US Saturday.

**Comment by noelherrick** [comment] 2017-10-21 04:08
@jnankin I'm not able to reproduce this issue - I added a test that covers this case and the code works as excepted, throwing an exception if a JSON error is returned.

**Comment by jnankin** [comment] 2017-10-22 01:13
Ok thanks

**Comment by noelherrick** [comment] 2018-01-21 01:02
Closing for now.

**Closed by noelherrick** 2018-01-21 01:02 UTC
